const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const elements=new Map();
const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:'',dataset:{},setAttribute(){},classList:{toggle(){}},disabled:false});return elements.get(id);};
const context=vm.createContext({console,document:{getElementById:element,querySelector:()=>element('switch'),querySelectorAll:()=>[],addEventListener(){}},location:{hash:''},history:{pushState(){}},window:{scrollTo(){}},setInterval(){},fetch:async()=>{throw Error('Unexpected network access');}});
vm.runInContext(readFileSync('app/lab.js','utf8'),context);
const run=code=>vm.runInContext(code,context);
(async()=>{
 const source=readFileSync('app/lab.js','utf8');
 const ids=new Set([...source.matchAll(/id="([A-Za-z][\w-]*)"/g)].map(m=>m[1]));
 for(const match of source.matchAll(/onsubmit="(\w+)\(/g))
   assert.equal(ids.has(match[1]),false,'form controls must not shadow the submit handler');
 run(`globalThis.savedRender=renderLab;globalThis.renderCount=0;renderLab=()=>renderCount++;labOpen('lab',undefined,false)`);
 assert.equal(run('renderCount'),1,'returning to dashboard must render the restored comparison mode');
 run('renderLab=savedRender');
 run(`labData={status:{workspace_mode:'blank',rounds:[{round:1,rows:[{baseline_pq:9}]}]},job:{result:{status:'ok',run_id:'stale'}}}`);
 assert.equal(run('labCurrent().result'),null,'blank workspace must never display an old result');
 run(`labData={status:{experiment_id:'new',workspace_mode:'experiment',baseline:'v1',rounds:[{experiment_id:'old',round:1}]},job:{state:'idle'}}`);
 assert.equal(run('labCurrent().result'),null,'establishing a new baseline must not revive prior experiment results');
 run(`labData={status:{rounds:[{round:1,rows:[]}]},job:{state:'idle'}}`);
 assert.match(run('labReview()'),/当前没有待复核结果/,'history cannot be approved again');
 run(`labData={status:{benchmark:{ready:true}},job:{state:'done',result:{status:'ok',run_id:'r1',baseline:'v1',candidate:'v2',rows:[],blind_pairs:[],decision:{action:'accept',reason:'test'}}}};labRunStatus()`);
 assert.equal(element('labStart').disabled,true,'pending results cannot be overwritten by another run');
 assert.match(element('labRunStatus').innerHTML,/进入试听复核/);
 run(`labData.job={state:'running',done:7,total:26,events:[]};labRunStatus()`);
 assert.match(element('labRunStatus').innerHTML,/value="7"/);
 assert.match(element('labRunStatus').innerHTML,/停止本轮/);
 run(`labData.job={state:'error',message:'model unavailable'};labRunStatus()`);
 assert.equal(element('labStart').disabled,false,'failed runs can retry when prerequisites are ready');
 run(`labData.status.benchmark.ready=false;labRunStatus()`);
 assert.equal(element('labStart').disabled,true,'missing prerequisites must block execution');
 run(`labData={status:{},job:{result:{status:'ok',run_id:'r1',baseline:'v1',candidate:'v2',rows:[],blind_pairs:[],decision:{action:'accept'}}}};labReviewRun='r1';labDialog=(t,b,a)=>{globalThis.confirmAction=a};labGet=async()=>({result:{run_id:'replaced'}});labApplyDialog()`);
 await assert.rejects(run('confirmAction()'),/结果已变化/,'stale confirmation cannot write a different run');
 run(`labData={status:{config:{matrix:{source:'golden'}}},job:{state:'idle'}};globalThis.calls=[];labPost=async(u,p)=>{calls.push([u,p]);return {status:'ok'}};labRefresh=async()=>{};labRunStatus=()=>{}`);
 element('labBaseline').value='v1';element('labCandidate').value='v2';
 await run('labSubmitRun({preventDefault(){}})');
 assert.deepEqual(JSON.parse(run('JSON.stringify(calls.map(c=>c[0]))')),['/api/loop/baseline','/api/loop/config','/api/loop/run']);
 assert.equal(run("calls.some(c=>c[0].includes('tts'))"),false,'evaluation must not generate TTS');
 console.log('PASS: blank isolation, history read-only, pending/run/error/readiness states, stale confirmation, first baseline and no TTS generation');
})().catch(e=>{console.error(e);process.exitCode=1;});
